export const PlanFeatureCode = {
  PUBLIC_PROFILE: 'PUBLIC_PROFILE',
  MARKETPLACE_LISTING: 'MARKETPLACE_LISTING',
  APPLICATIONS_MANAGEMENT: 'APPLICATIONS_MANAGEMENT',
  SCHOOL_MANAGEMENT: 'SCHOOL_MANAGEMENT',
  STUDENT_MANAGEMENT: 'STUDENT_MANAGEMENT',
  MANAGE_APPLICATIONS: 'MANAGE_APPLICATIONS',
  MANAGE_STUDENTS: 'MANAGE_STUDENTS',
} as const;

export type PlanFeatureCode =
  (typeof PlanFeatureCode)[keyof typeof PlanFeatureCode];
